# UniPi Student Notes
# CI Template - you shouldn't have a reason to edit this

sudo: required
language: generic
services: docker

script:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c 'cd src; tectonic "Programmazione di Interfacce.tex"'

after_success:
  - mv "src/Programmazione di Interfacce.pdf" programmazione-di-interfacce.pdf
  - body="**Ultima revisione**\n"
  - body+="[Download - Programmazione di Interfacce](https://github.com/$TRAVIS_REPO_SLUG/releases/download/continuous/programmazione-di-interfacce.pdf)";
    export UPLOADTOOL_BODY=$body
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh programmazione-di-interfacce.pdf

branches:
  except:
    - /^(?i:continuous)$/
